-- MySQL Script generated by MySQL Workbench
-- Thu Jan 14 21:40:09 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Delete existing tables
-- -----------------------------------------------------

DROP TABLE IF EXISTS categoria_productos CASCADE;
DROP TABLE IF EXISTS alertas CASCADE;
DROP TABLE IF EXISTS categorias CASCADE;
DROP TABLE IF EXISTS clientes CASCADE;
DROP TABLE IF EXISTS detalles_ventas CASCADE;
DROP TABLE IF EXISTS venta_detalles CASCADE;
DROP TABLE IF EXISTS movimientos CASCADE;
DROP TABLE IF EXISTS movimiento_categorias CASCADE;
DROP TABLE IF EXISTS pagos CASCADE;
DROP TABLE IF EXISTS pago_formas CASCADE;
DROP TABLE IF EXISTS productos CASCADE;
DROP TABLE IF EXISTS empresa CASCADE;
DROP TABLE IF EXISTS slide_principal CASCADE;
DROP TABLE IF EXISTS producto_categorias CASCADE;
DROP TABLE IF EXISTS cajas CASCADE;
DROP TABLE IF EXISTS monedas CASCADE;
DROP TABLE IF EXISTS web_productos CASCADE;
DROP TABLE IF EXISTS proveedores CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS usuarios CASCADE;
DROP TABLE IF EXISTS ventas CASCADE;
DROP TABLE IF EXISTS oauth_access_tokens CASCADE;
DROP TABLE IF EXISTS oauth_auth_codes CASCADE;
DROP TABLE IF EXISTS oauth_clients CASCADE;
DROP TABLE IF EXISTS oauth_personal_access_clients CASCADE;
DROP TABLE IF EXISTS oauth_refresh_tokens CASCADE;
DROP TABLE IF EXISTS password_resets CASCADE;

-- -----------------------------------------------------
-- Table `clientes`
-- -----------------------------------------------------
CREATE TABLE `clientes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(255) NOT NULL,
  `ruc` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NULL,
  `telefono` VARCHAR(255) NULL,
  `direccion` VARCHAR(255) NULL,
  `eliminado` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pago_formas`
-- -----------------------------------------------------
CREATE TABLE `pago_formas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `forma_pago` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `usuarios`
-- -----------------------------------------------------
CREATE TABLE `usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  `usuario` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `vendedor` TINYINT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ventas`
-- -----------------------------------------------------
CREATE TABLE `ventas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `factura_numero` VARCHAR(255) NULL,
  `condicion` TINYINT NOT NULL,
  `total` INT NOT NULL,
  `monto_pendiente` INT NOT NULL,
  `total_iva` INT NOT NULL,
  `numero_transaccion` VARCHAR(255) NULL,
  `operadora` VARCHAR(255) NULL,
  `fecha` DATE NOT NULL,
  `cliente_id` INT NOT NULL,
  `pago_forma_id` INT NOT NULL,
  `usuario_id` INT NOT NULL,
  `eliminado` TINYINT DEFAULT 0 NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idventas_UNIQUE` (`id`),
  INDEX `fk_ventas_clientes1_idx` (`cliente_id`),
  INDEX `fk_ventas_pago_formas1_idx` (`pago_forma_id`),
  INDEX `fk_ventas_usuarios1_idx` (`usuario_id`),
  CONSTRAINT `fk_ventas_clientes1`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `clientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ventas_pago_formas1`
    FOREIGN KEY (`pago_forma_id`)
    REFERENCES `pago_formas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ventas_usuarios1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `alertas`
-- -----------------------------------------------------
CREATE TABLE `alertas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `condicion` VARCHAR(255) NOT NULL,
  `estado` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `condicion_UNIQUE` (`condicion`),
  UNIQUE INDEX `id_UNIQUE` (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `producto_categorias`
-- -----------------------------------------------------
CREATE TABLE `producto_categorias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NULL,
  `descripcion` VARCHAR(255) NULL,
  `iva` INT NULL,
  `porcentaje_venta` INT NULL,
  `eliminado` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proveedores`
-- -----------------------------------------------------
CREATE TABLE `proveedores` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(255) NULL,
  `ruc` VARCHAR(255) NULL,
  `telefono` VARCHAR(255) NULL,
  `direccion` VARCHAR(255) NULL,
  `eliminado` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `productos`
-- -----------------------------------------------------
CREATE TABLE `productos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(255) NULL,
  `nombre` VARCHAR(255) NOT NULL,
  `descripcion` VARCHAR(255) NULL,
  `stock_actual` INT NOT NULL,
  `stock_minimo` INT NULL,
  `precio_venta` INT NOT NULL,
  `precio_compra` INT NOT NULL,
  `eliminado` TINYINT NOT NULL,
  `producto_categoria_id` INT NOT NULL,
  `proveedor_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_productos_producto_categorias1_idx` (`producto_categoria_id`),
  INDEX `fk_productos_proveedores1_idx` (`proveedor_id`),
  CONSTRAINT `fk_productos_producto_categorias1`
    FOREIGN KEY (`producto_categoria_id`)
    REFERENCES `producto_categorias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_productos_proveedores1`
    FOREIGN KEY (`proveedor_id`)
    REFERENCES `proveedores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `venta_detalles`
-- -----------------------------------------------------
CREATE TABLE `venta_detalles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cantidad` INT NOT NULL,
  `valor_guaranies` INT NOT NULL,
  `venta_id` INT NOT NULL,
  `productos_id` INT NOT NULL,
  `total_dolares` FLOAT NULL,
  `total_reales` FLOAT NULL,
  `total_pesos` INT NULL,
  INDEX `fk_venta_detalles_ventas_idx` (`venta_id`),
  INDEX `fk_venta_detalles_productos1_idx` (`productos_id`),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_venta_detalles_ventas`
    FOREIGN KEY (`venta_id`)
    REFERENCES `ventas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venta_detalles_productos1`
    FOREIGN KEY (`productos_id`)
    REFERENCES `productos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `movimiento_categorias`
-- -----------------------------------------------------
CREATE TABLE `movimiento_categorias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  `descripcion` VARCHAR(255) NULL,
  `eliminado` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `movimientos`
-- -----------------------------------------------------
CREATE TABLE `movimientos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NULL,
  `concepto` VARCHAR(255) NULL,
  `tipo_movimiento` TINYINT NULL,
  `monto` INT NULL,
  `proveedor_id` INT NOT NULL,
  `movimiento_categoria_id` INT NOT NULL,
  `eliminado` TINYINT DEFAULT 0 NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_movimientos_proveedores1_idx` (`proveedor_id`),
  INDEX `fk_movimientos_movimiento_categorias1_idx` (`movimiento_categoria_id`),
  CONSTRAINT `fk_movimientos_proveedores1`
    FOREIGN KEY (`proveedor_id`)
    REFERENCES `proveedores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_movimientos_movimiento_categorias1`
    FOREIGN KEY (`movimiento_categoria_id`)
    REFERENCES `movimiento_categorias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pagos`
-- -----------------------------------------------------
CREATE TABLE `pagos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `monto` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `venta_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pagos_ventas1_idx` (`venta_id`),
  CONSTRAINT `fk_pagos_ventas1`
    FOREIGN KEY (`venta_id`)
    REFERENCES `ventas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empresa`
-- -----------------------------------------------------
CREATE TABLE `empresa` (
  `nombre_web` VARCHAR(255) NULL,
  `direccion` VARCHAR(255) NULL,
  `telefono` VARCHAR(255) NULL,
  `razon_social` VARCHAR(255) NULL,
  `servicios` VARCHAR(255) NULL,
  `quienes_somos` MEDIUMTEXT NULL,
  `ubicacion` MEDIUMTEXT NULL,
  `logo` VARCHAR(255) NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `slide_principal`
-- -----------------------------------------------------
CREATE TABLE `slide_principal` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `imagen` VARCHAR(255) NOT NULL,
  `precio` INT NULL,
  `descripcion` VARCHAR(255) NULL,
  `nombre` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `web_productos`
-- -----------------------------------------------------
CREATE TABLE `web_productos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `imagen` VARCHAR(255) NOT NULL,
  `producto` VARCHAR(255) NULL,
  `precio` INT NULL,
  `nombre` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `monedas`
-- -----------------------------------------------------
CREATE TABLE `monedas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  `simbolo` VARCHAR(255) NULL,
  `valor` INT NULL,
  `predeterminada` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cajas`
-- -----------------------------------------------------
CREATE TABLE `cajas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `monto_apertura` INT NOT NULL,
  `monto_cierre` INT NULL,
  `monto_total` INT NULL,
  `fecha` DATE NOT NULL DEFAULT NOW(),
  `venta_inicial` INT NULL,
  `venta_final` INT NULL,
  `pago_inicial` INT NULL,
  `pago_final` INT NULL,
  `movimiento_inicial` INT NULL,
  `movimiento_final` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cajas_ventas1_idx` (`venta_inicial`),
  INDEX `fk_cajas_ventas2_idx` (`venta_final`),
  INDEX `fk_cajas_pagos1_idx` (`pago_inicial`),
  INDEX `fk_cajas_pagos2_idx` (`pago_final`),
  INDEX `fk_cajas_movimientos1_idx` (`movimiento_inicial`),
  INDEX `fk_cajas_movimientos2_idx` (`movimiento_final`),
  CONSTRAINT `fk_cajas_ventas1`
    FOREIGN KEY (`venta_inicial`)
    REFERENCES `ventas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cajas_ventas2`
    FOREIGN KEY (`venta_final`)
    REFERENCES `ventas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cajas_pagos1`
    FOREIGN KEY (`pago_inicial`)
    REFERENCES `pagos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cajas_pagos2`
    FOREIGN KEY (`pago_final`)
    REFERENCES `pagos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cajas_movimientos1`
    FOREIGN KEY (`movimiento_inicial`)
    REFERENCES `movimientos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cajas_movimientos2`
    FOREIGN KEY (`movimiento_final`)
    REFERENCES `movimientos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
